server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
    encoding:
      force-response: true
      force: true
      charset: UTF-8
      enabled: true


spring:
  profiles:
    active: dev