server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
    encoding:
      force-response: true
      force: true
      charset: UTF-8
      enabled: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      init-connection-sqls: set names utf8mb4
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
      #初始化大小
      initialSize: 2
      #最小值
      minIdle: 2
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      #filters: stat,wall,log4j2
      filter:
        log4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    dynamic:
      primary: master_1
      datasource:
        master_1:
          url: jdbc:mysql://123.56.125.48:3306/storeroom_mgr?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
          username: wxy
          password: Xiao123...
          driver-class-name: com.mysql.cj.jdbc.Driver


  application:
    name: yh-service-school
management:
  endpoints:
    web:
      exposure:
        include: '*'


#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

jwt:
  SECRET: wxy#adminjwt
  ISS: wxyadmin
mybatis-plus:
  mapper-locations: classpath*:generator/*.xml
  type-aliases-package: com.wxy.dao
  type-enums-package: com.wxy.model.enums.**
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日
logging:
  level:
    root: error